name: Create Archive
on:
  push:
    tags:
    - 'release'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'remnant.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *.zip'
    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "remnant.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        
